font_size 16.0

dynamic_background_opacity yes
background_opacity 0.7

# `read-clipboard-ask read-primary-ask` - is not used here. probably a bad idea, but i need ssh neovim to not yell at me
clipboard_control write-clipboard write-primary read-clipboard read-primary

#input_delay 0
#repaint_delay 2
#sync_to_monitor no
#wayland_enable_ime no
