blur-background = false;
shadow = false
fading = false
corner-radius = 0

window-shader-fg = "shader.glsl";

backend = "glx";

active-opacity = 1.0;
inactive-opacity = 1.0;
frame-opacity = 1.0;

opacity-rule = [
    "95:class_g = 'obsidian'",
  "80:class_g = 'i3-bar' && !_NET_WM_STATE@:32a",
  "50:class_g = 'i3-frame' && !_NET_WM_STATE@:32a",
  "0:_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
];

# this doesn't work
rules = (
    {
        match = "name = 'flameshot' || "
                "class_g ?= 'Flameshot' || "
                "class_i ?= 'flameshot'";

        blur-background = false;
        blur-background-frame = false;
        shadow = false;
        corner-radius = 0

        window-shader-fg = "default";
    }
)

