blur-background = false;
shadow = false
fading = false
corner-radius = 0

window-shader-fg = "shader.glsl";

backend = "glx";

active-opacity = 1.0;
inactive-opacity = 1.0;
frame-opacity = 1.0;

opacity-rule = [
    "95:class_g = 'obsidian'"
];

# this doesn't work
rules = (
    {
        match = "name = 'flameshot' || "
                "class_g ?= 'Flameshot' || "
                "class_i ?= 'flameshot'";

        blur-background = false;
        blur-background-frame = false;
        shadow = false;
        corner-radius = 0

        window-shader-fg = "default";
    }
)

